feat: create validate.yml

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -34,11 +34,11 @@ jobs:
           
           echo "Changed files: $CHANGED_FILES"
           
-          INVALID_CHANGES=$(echo "$CHANGED_FILES" | grep -v -E '^src/|^\.github/' || true)
+          INVALID_CHANGES=$(echo "$CHANGED_FILES" | grep -v -E '^src/|^\.github/|package.json' || true)
           echo "Invalid changed files: $INVALID_CHANGES"
           
           if [ -n "$INVALID_CHANGES" ]; then
-            echo "Detected invalid changes outside 'src/' or '.github/' folders."
+            echo "Detected invalid changes outside 'src/', '.github/' folders or 'package.json' file."
             echo "Invalid changes: $INVALID_CHANGES"
             exit 1
           fi
@@ -49,6 +49,6 @@ jobs:
       - name: Install dependencies and run tests
         if: steps.check_files.outcome == 'success'
         run: |
-          cd /home/runner/work/js-ts-tasks/js-ts-tasks
+          cd js-ts-tasks
           npm install
           npm run test:local
